---
# yamllint disable rule:line-length
# yamllint disable rule:truthy

name: Build Feature Branch

on:
  workflow_dispatch:
  push:
    branches-ignore: 
      - master

jobs:

  validate_new_version:
    name: Validate new version
    runs-on: ubuntu-latest
    outputs:
      planned_version: ${{ steps.validate_new_version.outputs.planned_version }}
      version_file_exists: ${{ steps.validate_new_version.outputs.version_file_exists }}
      tag_hash: ${{ steps.validate_new_version.outputs.tag_hash }}
      can_create: ${{ steps.validate_new_version.outputs.can_create }}
      tag_exists: ${{ steps.validate_new_version.outputs.tag_exists }}
      branch_name: ${{ steps.validate_new_version.outputs.branch_name }}
      underscored_branch_name: ${{ steps.generate_tag_from_branch.outputs.underscored_branch_name }}

    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use latest released action
        id: validate_new_version
        uses: reinvented-stuff/validate-version-action@1.2.0
        with:
          version_filename: ".version"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          fail_on_error: false

      - name: Generate docker image tag out of the branch name
        id: generate_tag_from_branch
        shell: bash
        run: |
          _orig_branch_name="${{ steps.validate_new_version.outputs.branch_name }}"
          _underscored_branch_name=${_orig_branch_name//\//_}

          echo "underscored_branch_name=${_underscored_branch_name}"
          echo "underscored_branch_name=${_underscored_branch_name}" >> "${GITHUB_OUTPUT}"

      - name: Generate new/exists label for the version
        id: generate_new_exist_version_label
        shell: bash
        run: |
          _version_label="unknown"
          if [[ "${{ steps.validate_new_version.outputs.can_create }}" == "true" ]]; then
            _version_label="new"
          else
            _version_label="exists"
          fi

          echo "new_exist_version_label=${_version_label}"
          echo "new_exist_version_label=${_version_label}" >> "${GITHUB_OUTPUT}"

      - name: Send out notification about workflow start
        uses: rest-gateway/notification-action@1.0.9
        with:
          message: |-
            Workflow: <b>${{ github.repository }}</b>
            version: ${{ steps.validate_new_version.outputs.planned_version }} (${{ steps.generate_new_exist_version_label.outputs.new_exist_version_label }})
            branch: ${{ steps.validate_new_version.outputs.branch_name }}

          recipient: "${{ secrets.NOTIFICATIONS_DEFAULT_RECIPIENT }}"
          rest_gateway_url: "${{ secrets.REST_GATEWAY_API_URL }}"
          rest_gateway_token: "${{ secrets.REST_GATEWAY_TOKEN }}"
          rest_gateway_bot_name: "${{ secrets.REST_GATEWAY_BOT_NAME }}"


  docker_images:
    name: Build Docker images

    outputs:
      job_status: ${{ job.status }}
      artifact_name: ${{ steps.set_artifact_name.outputs.name }}

    strategy:
      matrix:
        build_env:
          - env_name: dev
            env_suffix: -dev

    runs-on: ubuntu-latest

    needs:
      - validate_new_version

    env:
      PLANNED_VERSION: ${{ needs.validate_new_version.outputs.planned_version }}
      TAG_HASH: ${{ needs.validate_new_version.outputs.tag_hash }}
      CAN_CREATE_RELEASE: ${{ needs.validate_new_version.outputs.can_create }}
      TAG_EXISTS: ${{ needs.validate_new_version.outputs.tag_exists }}
      BRANCH_NAME: ${{ needs.validate_new_version.outputs.branch_name }}
      UNDERSCORED_BRANCH_NAME: ${{ needs.validate_new_version.outputs.underscored_branch_name }}

      APP_NAME: "airquality_exporter"

    if: >
      github.event_name == 'push'

    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Build Docker image - ${{ matrix.build_env.env_name }}
        id: build_docker_image
        uses: reinvented-stuff/build-docker-image-action@2.6.0
        with:
          registry_address: "ghcr.io"
          registry_username: "${{ github.actor }}"
          registry_token: "${{ secrets.GITHUB_TOKEN }}"
          name: "${{ github.repository }}"
          planned_version: "${{ env.PLANNED_VERSION }}-${{ env.UNDERSCORED_BRANCH_NAME }}${{ matrix.build_env.env_suffix }}"
          skip_branch_suffix: true
          build_args: |
            APP_VERSION=${{ env.PLANNED_VERSION }}-${{ env.UNDERSCORED_BRANCH_NAME }}${{ matrix.build_env.env_suffix }}
            BUILD_ENV=${{ matrix.build_env.env_name }}


      - name: Send out notification about docker image build
        uses: rest-gateway/notification-action@1.0.9
        with:
          message: |
            Docker image: <b>${{ env.APP_NAME }}</b> v${{ env.PLANNED_VERSION }} (${{ env.BRANCH_NAME }})
            BUILD_ENV: ${{ matrix.build_env.env_name }}

            <code>${{ steps.build_docker_image.outputs.image_full_name }}</code>
          recipient: "${{ secrets.NOTIFICATIONS_DEFAULT_RECIPIENT }}"
          rest_gateway_url: "${{ secrets.REST_GATEWAY_API_URL }}"
          rest_gateway_token: "${{ secrets.REST_GATEWAY_TOKEN }}"
          rest_gateway_bot_name: "${{ secrets.REST_GATEWAY_BOT_NAME }}"

...
